name: SourceZero CodeReview
on:
  pull_request:
    types:
      - opened
permissions: write-all
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install Dependencies
        run: poetry install
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Code Review
        run: poetry run python3 codereview/main.py ${{ secrets.GITHUB_TOKEN }} $EXCLUDE
        env:
          EXCLUDE: "yarn.lock,dist/**"