name: SourceZero CodeReview
on:
  pull_request:
    types:
      - opened
permissions: write-all
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.0
          installer-parallel: true
      - name: Install Dependencies
        run: poetry install
      - name: Code Review
        run: poetry run python3 codereview/main.py
        env:
          EXCLUDE: "yarn.lock,dist/**"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}